packages: []

catalog:
  "@vue/tsconfig": ^0.7.0

catalogMode: strict

catalogs:
  build:
    "@shikijs/markdown-it": ^3.8.0
    "@shikijs/transformers": ^3.8.0
    "@shikijs/twoslash": ^3.8.0
    "@unocss/preset-web-fonts": ^66.3.3
    "@vitejs/plugin-vue": ^6.0.0
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-link-attributes: ^4.0.1
    markdown-it-magic-link: ^0.1.4
    markdown-it-table-of-contents: ^0.9.0
    unocss: ^66.3.3
    unplugin-auto-import: ^19.3.0
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-markdown: ^29.1.0
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.4
    vite-plugin-inspect: ^11.3.0
    vite-plugin-optimize-exclude: ^0.0.1
    vite-ssg: ^28.0.0
    vite-svg-loader: ^5.1.0
    vue-tsc: "^3.0.5"
  dev:
    "@antfu/eslint-config": ^4.17.0
    "@iconify/json": ^2.2.359
    "@octokit/core": ^7.0.3
    "@octokit/rest": ^22.0.0
    "@unocss/eslint-plugin": ^66.4.1
    ansis: ^4.1.0
    cross-env: ^7.0.3
    degit: ^2.8.4
    diacritics: ^1.3.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    exifreader: ^4.31.1
    fast-glob: ^3.3.3
    feed: ^5.1.0
    fs-extra: ^11.3.0
    lint-staged: ^16.1.2
    pathe: ^2.0.3
    pnpm: ^10.13.1
    prompts: ^2.4.2
    rimraf: ^6.0.1
    sharp: 0.32.6
    simple-git: ^3.28.0
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ~5.8.3
  frontend:
    "@antfu/utils": ^9.2.0
    "@unhead/vue": ^2.0.12
    "@unocss/reset": ^66.3.3
    "@vueuse/core": ^13.5.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    dayjs: ^1.11.13
    floating-vue: ^5.2.2
    matter-attractors: ^0.1.6
    matter-js: ^0.20.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    pixi.js: ^8.11.0
    shiki: ^3.8.0
    shiki-magic-move: ^1.1.0
    simplex-noise: ^4.0.3
    vue: ^3.5.17
    vue-router: ^4.5.1
    vue-router-better-scroller: ^0.0.0
  types:
    "@types/d3-hierarchy": ^3.1.7
    "@types/d3-shape": ^3.1.7
    "@types/degit": ^2.8.6
    "@types/diacritics": ^1.3.3
    "@types/fs-extra": ^11.0.4
    "@types/markdown-it": ^14.1.2
    "@types/markdown-it-link-attributes": ^3.0.5
    "@types/node": ^24.2.0
    "@types/nprogress": ^0.2.3
    "@types/prompts": ^2.4.9

onlyBuiltDependencies:
  - esbuild
  - exifreader
  - sharp
  - simple-git-hooks
  - unrs-resolver
